### ISSUE TITLE
[BUG] Fix routing

### ISSUE THREAD

**Issue by vasylpopovych** [vasylpopovych/travel-app#1]
- after refresh main page, with route '/', page don`t open. It happened only on localhost
- on deploying. After trying load 404 page, app don`t redirect to main page.

**Comment by Evcat6** [comment]
on deployment you can solve problem by creating netlify.toml file in root of project and write this inside of file: 
`[[redirects]]`
`  from = "/*"`
`  to = "/"`
`  status = 200`

**Comment by vasylpopovych** [comment]
> on deployment you can solve problem by creating netlify.toml file in root of project and write this inside of file: `[[redirects]]` ` from = "/*"` ` to = "/"` ` status = 200

Thanks, bro!) It helped!
